"""Add auth relationships

Revision ID: 61dc48f26abf
Revises: bad198f4168a
Create Date: 2025-11-06 12:46:00.495459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61dc48f26abf'
down_revision: Union[str, Sequence[str], None] = 'bad198f4168a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_organization_owner', 'organization', 'user', ['owner_id'], ['id'])
    op.add_column('user', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_organization_member', 'user', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'organization_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'owner_id')
    # ### end Alembic commands ###
