"""Change the organization-member relationship to a many-to-many one.

Revision ID: 0d3301d6795c
Revises: 5ca2b30a19e5
Create Date: 2026-01-06 16:18:25.437250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3301d6795c'
down_revision: Union[str, Sequence[str], None] = '5ca2b30a19e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_members_join_table',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'member_id')
    )
    op.drop_constraint(op.f('fk_organization_member'), 'user', type_='foreignkey')
    op.drop_column('user', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_organization_member'), 'user', 'organization', ['organization_id'], ['id'])
    op.drop_table('organization_members_join_table')
    # ### end Alembic commands ###
