from src.auth.models import Organization, User


def test_relationships(TestSession):
    # Testing third party tools is bad, I know. I just want to make sure that the relationships
    # work as expected, because the autogenerated FK migration looks a bit weird.

    organization = Organization(name="nerv")
    with TestSession() as session:
        session.add(organization)
        session.commit()
        organization_id = organization.id
        
    owner = User(
        email="gendo@nerv.jp", 
        username="gendo", 
        password_hash="not_a_hash", 
        owned_organization=organization,
        # organization=organization,  # For some reason can't be added along with owned_organization
    )
    with TestSession() as session:
        session.add(owner)
        session.commit()
    
    owner.organization = organization
    member_1 = User(
        email="fuyutsuki@nerv.jp",
        username="fuyutsuki",
        password_hash="not_a_hash",
        organization=organization,
    )
    member_2 = User(
        email="naoko@nerv.jp",
        username="naoko",
        password_hash="not_a_hash",
        organization=organization,
    )

    with TestSession(expire_on_commit=False) as session:
        session.add(owner)
        session.add(member_1)
        session.add(member_2)
        session.commit()

        org = session.get(Organization, organization_id)
        org.owner
        org.members

    # Test does NOT work now        
    assert org.owner.id == owner.id
    assert len(org.members) == 3    
    assert owner in org.members
    assert member_1 in org.members
    assert member_2 in org.members
